version: 1.0.0

parameters:
  components:
    uptrace:
      namespace:
        type: string
        required: false
        default: "uptrace"
      releaseName:
        type: string
        required: false
        default: "uptrace"
      valuesFiles:
        type: string
        required: false
        default: "values.yaml values-override.yaml"
      minHelmVersion:
        type: string
        required: false
        default: ""
      minKubectlVersion:
        type: string
        required: false
        default: ""
      imageRepository:
        type: string
        default: "uptrace/uptrace"
      imageTag:
        type: string
        default: "1.7.0"
      replicaCount:
        type: integer
        default: 1
