components:
  - name: istio
    path: 
    - kubernetes/components/istio/namespace.yaml.tmpl
    - kubernetes/components/istio/operator.yaml.tmpl
    - kubernetes/components/istio/kustomization.yaml.tmpl
    - kubernetes/components/istio/install.tmpl
    - kubernetes/components/istio/validate.tmpl
    install: bash ./install
    installType: custom
    check: bash ./validate
  - name: sealed-secret
    path:
    - kubernetes/components/sealed-secret/kustomization.yaml.tmpl
    args:
    - kubernetes/components/sealed-secret/args.yaml
    installType: kubectl
  - name: external-secrets-operator
    path:
    - kubernetes/components/external-secrets-operator/Chart.yaml
    - kubernetes/components/external-secrets-operator/values.yaml.tmpl
    - kubernetes/components/external-secrets-operator/install.tmpl
    - kubernetes/components/external-secrets-operator/validate.tmpl
    args:
    - kubernetes/components/external-secrets-operator/args.yaml
    install: bash ./install
    installType: custom
    check: bash ./validate
  - name: external-secrets
    path:
    - kubernetes/components/external-secrets/namespace.yaml.tmpl
    - kubernetes/components/external-secrets/cluster-secret-store.yaml.tmpl
    - kubernetes/components/external-secrets/kustomization.yaml.tmpl
    installType: kubectl
    dependencies:
      - external-secrets-operator
  - name: victoria-metrics-operator
    path:
    - kubernetes/components/victoria-metrics-operator/Chart.yaml
    - kubernetes/components/victoria-metrics-operator/Chart.lock
    - kubernetes/components/victoria-metrics-operator/values.yaml
    - kubernetes/components/victoria-metrics-operator/values-override.yaml.tmpl
    - kubernetes/components/victoria-metrics-operator/templates/vminsert-internal-lb.yaml
    - kubernetes/components/victoria-metrics-operator/templates/recoding-rules/node-exporter.yaml
    - kubernetes/components/victoria-metrics-operator/templates/recoding-rules/k8s.yaml
    - kubernetes/components/victoria-metrics-operator/install.tmpl
    - kubernetes/components/victoria-metrics-operator/validate.tmpl
    install: bash ./install
    installType: custom
    check: bash ./validate
    dependencies:
      - istio
  - name: grafana
    path:
    - kubernetes/components/grafana/Chart.yaml
    - kubernetes/components/grafana/Chart.lock
    - kubernetes/components/grafana/values.yaml
    - kubernetes/components/grafana/values-override.yaml.tmpl
    - kubernetes/components/grafana/templates/external-secret.yaml
    - kubernetes/components/grafana/install.tmpl
    install: bash ./install
    installType: custom
    dependencies:
      - victoria-metrics-operator
  - name: victoria-metrics
    path:
    - kubernetes/components/victoria-metrics/kustomization.yaml
    - kubernetes/components/victoria-metrics/vmalertmanagerconfig.yaml.tmpl
    - kubernetes/components/victoria-metrics/slack-webhook-url.yaml
    - kubernetes/components/victoria-metrics/alert-rules/kustomization.yaml
    - kubernetes/components/victoria-metrics/alert-rules/vmoperator.yaml
    - kubernetes/components/victoria-metrics/alert-rules/vmhealth.yaml
    - kubernetes/components/victoria-metrics/alert-rules/vmcluster.yaml
    - kubernetes/components/victoria-metrics/alert-rules/vmagent.yaml
    - kubernetes/components/victoria-metrics/alert-rules/node-exporter.yaml
    - kubernetes/components/victoria-metrics/alert-rules/llm-matcher.yaml
    - kubernetes/components/victoria-metrics/alert-rules/kube-state-metrics.yaml
    - kubernetes/components/victoria-metrics/alert-rules/istio.yaml
    - kubernetes/components/victoria-metrics/install.tmpl
    install: bash ./install
    installType: custom
    dependencies:
      - victoria-metrics-operator
  - name: cnpg
    path:
    - kubernetes/components/cnpg/Chart.yaml
    - kubernetes/components/cnpg/Chart.lock
    - kubernetes/components/cnpg/values.yaml
    - kubernetes/components/cnpg/values-override.yaml.tmpl
    - kubernetes/components/cnpg/install.tmpl
    args:
    - kubernetes/components/cnpg/args.yaml
    install: bash ./install
    installType: custom
  - name: redis
    path:
    - kubernetes/components/redis/Chart.yaml
    - kubernetes/components/redis/values.yaml
    - kubernetes/components/redis/values-override.yaml.tmpl
    - kubernetes/components/redis/install.tmpl
    args:
    - kubernetes/components/redis/args.yaml
    install: bash ./install
    installType: custom
    dependencies:
      - external-secrets
  - name: paradedb
    path:
    - kubernetes/components/paradedb/Chart.yaml
    - kubernetes/components/paradedb/values.yaml
    - kubernetes/components/paradedb/values-override.yaml.tmpl
    - kubernetes/components/paradedb/install.tmpl
    args:
    - kubernetes/components/paradedb/args.yaml
    install: bash ./install
    installType: custom
    dependencies:
      - cnpg
  - name: kafka
    path:
    - kubernetes/components/kafka/Chart.yaml
    - kubernetes/components/kafka/values.yaml
    - kubernetes/components/kafka/values-override.yaml.tmpl
    - kubernetes/components/kafka/install.tmpl
    args:
    - kubernetes/components/kafka/args.yaml
    install: bash ./install
    installType: custom
  - name: loki
    path:
    - kubernetes/components/loki/Chart.yaml
    - kubernetes/components/loki/values.yaml
    - kubernetes/components/loki/values-override.yaml.tmpl
    - kubernetes/components/loki/install.tmpl
    args:
    - kubernetes/components/loki/args.yaml
    install: bash ./install
    installType: custom
  - name: otel-collector
    path:
    - kubernetes/components/otel-collector/Chart.yaml
    - kubernetes/components/otel-collector/values.yaml
    - kubernetes/components/otel-collector/values-override.yaml.tmpl
    - kubernetes/components/otel-collector/install.tmpl
    args:
    - kubernetes/components/otel-collector/args.yaml
    install: bash ./install
    installType: custom
  - name: n9e
    path:
    - kubernetes/components/n9e/Chart.yaml
    - kubernetes/components/n9e/values.yaml
    - kubernetes/components/n9e/values-override.yaml.tmpl
    - kubernetes/components/n9e/install.tmpl
    args:
    - kubernetes/components/n9e/args.yaml
    install: bash ./install
    installType: custom
    dependencies:
      - victoria-metrics-operator
  - name: uptrace
    path:
    - kubernetes/components/uptrace/Chart.yaml
    - kubernetes/components/uptrace/values.yaml
    - kubernetes/components/uptrace/values-override.yaml.tmpl
    - kubernetes/components/uptrace/install.tmpl
    args:
    - kubernetes/components/uptrace/args.yaml
    install: bash ./install
    installType: custom
    dependencies:
      - cnpg
  - name: bytebase
    path:
    - kubernetes/components/bytebase/Chart.yaml
    - kubernetes/components/bytebase/values.yaml
    - kubernetes/components/bytebase/values-override.yaml.tmpl
    - kubernetes/components/bytebase/templates/_helpers.tpl
    - kubernetes/components/bytebase/templates/statefulset.yaml
    - kubernetes/components/bytebase/templates/service.yaml
    - kubernetes/components/bytebase/templates/secretproviderclass.yaml
    - kubernetes/components/bytebase/install.tmpl
    args:
    - kubernetes/components/bytebase/args.yaml
    install: bash ./install
    installType: custom
  - name: juicefs
    path:
    - kubernetes/components/juicefs/kustomization.yaml.tmpl
    - kubernetes/components/juicefs/namespace.yaml.tmpl
    - kubernetes/components/juicefs/serviceaccount.yaml.tmpl
    - kubernetes/components/juicefs/secret.yaml.tmpl
    - kubernetes/components/juicefs/storageclass.yaml.tmpl
    - kubernetes/components/juicefs/job-format.yaml.tmpl
    - kubernetes/components/juicefs/statefulset.yaml.tmpl
    - kubernetes/components/juicefs/service.yaml.tmpl
    - kubernetes/components/juicefs/install.tmpl
    args:
    - kubernetes/components/juicefs/args.yaml
    install: bash ./install
    installType: custom
    dependencies:
      - external-secrets
