version: 1.0.0
global: {}
projects:
  - name: app
    components:
      - name: 0-external-secrets-operator
        parameters:
          namespace: external-secrets-operator
          release-name: external-secrets-operator
          replica-count: 1
          image-tag: "v2.0.1"
          min-helm-version: "v3.18.4"
          min-kubectl-version: "1.24"
      - name: 0-external-secrets
        parameters:
          namespace: external-secrets
          project-id: app
          secret-manager-service-account-email: sa-sm-accessor@app.iam.gserviceaccount.com
          service-account-name: external-secrets-sa
      - name: 0-sealed-secret
        parameters:
          namespace: sealed-secret
          controller-manifest-url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.32.2/controller.yaml
      - name: 1-istio
        parameters:
          namespace: istio
          istio-operator-version: 1.20.0
          istio-version: 1.20.0
          istio-namespace: istio
          istio-operator-namespace: istio-operator
          istio-operator-service-account: istio-operator
      - name: 2-argocd
        parameters:
          namespace: argocd
          argocd-url: https://app.example.com/argocd
          argocd-manifest-url: https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.7/manifests/install.yaml
          dex-config: {}
          RBACPolicies: []
          RBACRoleBindings: []
      - name: 3-victoria-metrics-operator
        parameters:
          namespace: monitoring-vm
          release-name: victoriametrics
          cluster: app
          env: app
          remote-write-url: "http://vminsert-victoriametrics-vmks.monitoring-vm.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
          vmagent-cpu-limit: "1"
          vmagent-memory-limit: "1Gi"
          vmagent-cpu-request: "300m"
          vmagent-memory-request: "512Mi"
      - name: 4-victoria-metrics
        parameters:
          namespace: monitoring-vm
          alert-cluster: app
      - name: 4-grafana
        parameters:
          namespace: grafana
          release-name: grafana
          image-tag: "12.3.1"
          root-url: "https://grafana.example.com"
          vm-datasource-url: "http://vmselect-victoriametrics-vmks.monitoring-vm.svc.cluster.local:8481/select/0/prometheus"
          loki-datasource-url: "http://loki-gateway.loki.svc.cluster.local"
          hosted-domain: "example.com"
