---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-google-auth
  namespace: grafana
spec:
  refreshInterval: 1m # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: grafana-google-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: grafana-google-auth 
